#-------------------------------------------------------------------------------
# Note for using the rate-limiting:
#   The comment part won't be copied if you use the subgenerator docker-compose
#   you have to manually copy it
#-------------------------------------------------------------------------------
version: '2'
services:
    proxy-app:
        image: proxy
        external_links:
            - proxy-mysql:mysql
            # Uncomment to have Cassandra working with the gateway
            # - proxy-cassandra:cassandra
            - proxy-elasticsearch:elasticsearch
            - kafka:kafka
            - zookeeper:zookeeper
            - jhipster-registry:registry
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_CLOUD_CONFIG_URI=http://admin:admin@registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/proxy?useUnicode=true&characterEncoding=utf8&useSSL=false
            - SPRING_DATA_CASSANDRA_CONTACTPOINTS=cassandra
            - JHIPSTER_SLEEP=30 # gives time for the Cassandra cluster to start and execute the migration scripts
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
            - SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=kafka
            - SPRING_CLOUD_STREAM_KAFKA_BINDER_ZK_NODES=zookeeper
        ports:
            - 8080:8080
    proxy-mysql:
        extends:
            file: mysql.yml
            service: proxy-mysql
    # Uncomment to have Cassandra working with the gateway
    # proxy-cassandra:
    #     extends:
    #         file: cassandra-cluster.yml
    #         service: proxy-cassandra
    # proxy-cassandra-migration:
    #     extends:
    #         file: cassandra-migration.yml
    #         service: proxy-cassandra-migration
    #     environment:
    #         - CREATE_KEYSPACE_SCRIPT=create-keyspace-prod.cql
    proxy-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: proxy-elasticsearch
    kafka:
        extends:
            file: kafka.yml
            service: kafka
        environment:
            - KAFKA_ADVERTISED_HOST_NAME=kafka
    zookeeper:
        extends:
            file: kafka.yml
            service: zookeeper
    jhipster-registry:
        extends:
            file: jhipster-registry.yml
            service: jhipster-registry
        environment:
            - SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS=file:./central-config/docker-config/
