version: '2'
services:
    proxy-cassandra:
        container_name: proxy-cassandra
        image: cassandra:3.9
        # volumes:
        #     - ~/volumes/jhipster/proxy/cassandra/:/var/lib/cassandra/data
        ports:
            - 7000:7000
            - 7001:7001
            - 7199:7199
            - 9042:9042
            - 9160:9160
    proxy-cassandra-node:
        image: cassandra:3.9
        links:
            - proxy-cassandra:seed
        environment:
            - CASSANDRA_SEEDS=seed
    proxy-cassandra-migration:
        extends:
            file: cassandra-migration.yml
            service: proxy-cassandra-migration
        links:
            - proxy-cassandra
        environment:
            - CREATE_KEYSPACE_SCRIPT=create-keyspace-prod.cql
